name: Terraform CI-CD
on:
  workflow_dispatch:
## TODO: Hands-on 3: uncomment the following 3 lines to trigger for push on main
  push:
    branches:
      - main

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
## Setup Section
    # This action is a very common action, used to download the repo then cd to its folder
    - name: Download repo and cd to the repo folder
      uses: actions/checkout@v2

    # This is an aws provided action, that logs in into an AWS account using an OIDC connection.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # Hands-on 3: Replace this with your OIDC role, elgama
        role-to-assume: arn:aws:iam::398023770855:role/deployment-role
        aws-region: us-west-2

    ## TODO: Hands-on 3: Add a step to Setup terraform on the GitHub Runner using this action https://github.com/hashicorp/setup-terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    # Terraform init to download providers/modules and connect to backend
    - name: Terraform Init
      run: terraform init

## CI Section:
    # Make sure code is correctly formatted
    - name: Make sure code is formatted
      run: terraform fmt -check

    # Make sure code doesn't have any syntax errors
    - name: Make sure code is valid
      run: terraform validate

    # Do a Terraform plan to see what are the changes to be done, note that Terraform can't guarantee to take apply these changes if you run "terraform apply", because terraform apply would be run at a later stage with a potentially different state file.
    - name: Terraform Plan
      run: terraform plan

  terraform-cd:
    runs-on: ubuntu-latest
    needs: [ terraform-ci ] # to make the deployment sequential
    environment: prd
    steps:
## Setup Section
    # This action is a very common action, used to download the repo then cd to its folder
    - name: Download repo and cd to the repo folder
      uses: actions/checkout@v2

    # This is an aws provided action, that logs in into an AWS account using an OIDC connection.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # Hands-on 3: Replace this with your OIDC role, elgama
        role-to-assume: arn:aws:iam::398023770855:role/deployment-role
        aws-region: us-west-2

    ## TODO: Hands-on 3: Add a step to Setup terraform on the GitHub Runner using this action https://github.com/hashicorp/setup-terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    # Terraform init to download providers/modules and connect to backend
    - name: Terraform Init
      run: terraform init

## CD Section:
    # Deploy Terraform code
    - name: Terraform Apply
      run: terraform apply --auto-approve